var universities = {
    'algoma-university': 'Algoma University',
    'brock-university': 'Brock University',
    'carleton-university': 'Carleton University',
    'lakehead-university': 'Lakehead University',
    'laurentian-university': 'Laurentian University',
    'mcmaster-university': 'McMaster University',
    'ocad-university': 'OCAD University',
    'ontario-tech-university': 'Ontario Tech University',
    'queen-s-university': 'Queen's University',
    'royal-military-college-of-canada': 'Royal Military College of Canada',
    'toronto-metropolitan-university': 'Toronto Metropolitan University',
    'trent-university': 'Trent University',
    'trent-university-durham-greater-toronto-area': 'Trent University – Durham Greater Toronto Area',
    'universit-de-hearst': 'Université de Hearst',
    'universit-de-l-ontario-fran-ais': 'Université de l'Ontario français',
    'university-of-guelph': 'University of Guelph',
    'university-of-guelph-humber': 'University of Guelph-Humber',
    'university-of-ottawa': 'University of Ottawa',
    'university-of-ottawa-saint-paul-university': 'University of Ottawa – Saint Paul University',
    'university-of-toronto': 'University of Toronto',
    'university-of-toronto-mississauga': 'University of Toronto – Mississauga',
    'university-of-toronto-scarborough': 'University of Toronto – Scarborough',
    'university-of-waterloo': 'University of Waterloo',
    'university-of-waterloo-conrad-grebel-university-college': 'University of Waterloo – Conrad Grebel University College',
    'university-of-waterloo-renison-university-college': 'University of Waterloo – Renison University College',
    'university-of-waterloo-st-jerome-s-university': 'University of Waterloo – St. Jerome's University',
    'university-of-waterloo-united-college': 'University of Waterloo – United College',
    'university-of-windsor': 'University of Windsor',
    'western-university': 'Western University',
    'western-university-brescia-university-college': 'Western University – Brescia University College',
    'western-university-huron-university-college': 'Western University – Huron University College',
    'western-university-king-s-university-college': 'Western University – King's University College',
    'wilfrid-laurier-university': 'Wilfrid Laurier University',
    'wilfrid-laurier-university-brantford-campus': 'Wilfrid Laurier University – Brantford Campus',
    'york-university': 'York University',
    'york-university-glendon-campus': 'York University – Glendon Campus',
};